# Generated by Django 4.0.5 on 2022-07-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=30, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d', verbose_name='Photo')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
