# Generated by Django 4.0.5 on 2022-07-10 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='car',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=20, verbose_name='Price'),
        ),
    ]
