# Generated by Django 4.0.5 on 2022-07-10 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_car_options_car_date_time_alter_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('BMW', 'BMW'), ('Toyota', 'Toyota'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Nissan', 'Nissan'), ('Audi', 'Audi'), ('Lamborghini', 'Lamborghini'), ('Volkswagen', 'Volkswagen'), ('Mercedes', 'Mercedes')], max_length=50, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date_Time'),
        ),
    ]
